### ISSUE TITLE
登录之后出错

### ISSUE THREAD

**Issue by linzehui** [gunerguner/stockManager#10]
你好，首先感谢你开发的记录网页。
在使用的时候遇到一些问题，想请教一下应怎么fix。
在登录之后出现
<img width="389" alt="image" src="https://user-images.githubusercontent.com/16056955/135712691-30bf9d15-40f2-4602-80a9-7f69a12d8a6a.png">

且在命令行中有

[ERROR][2021-10-02 10:34:46,995][log.py:230]Internal Server Error: /api/
Traceback (most recent call last):
  File "/Users/linzehui/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/linzehui/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/linzehui/Desktop/stockManager/stockManager/backend/stockViews.py", line 27, in show_stocks
    merged_data = stock_caculator.caculate_target()
  File "/Users/linzehui/Desktop/stockManager/stockManager/backend/caculator.py", line 26, in caculate_target
    to_return["overall"] = self.__caculate_overall_target(stock_list)
  File "/Users/linzehui/Desktop/stockManager/stockManager/backend/caculator.py", line 332, in __caculate_overall_target
    origin_cash = float(Info.objects.get(key="originCash").value)
  File "/Users/linzehui/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/linzehui/.local/lib/python3.7/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
backend.models.Info.DoesNotExist: Info matching query does not exist.
[02/Oct/2021 10:34:46] "GET /api/ HTTP/1.1" 500 82030

不知道作者是否遇到过，可否提示一下应怎么解决？

**Comment by gunerguner** [comment]
数据库里的meta那张表需要originCash字段，可以看一下代码里的用法。
